apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: reproducer-03460076
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: This is just an example.
  destinations:
    - name: in-cluster
      namespace: reproducer-03460076
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/gmeghnag/03460076'
status: {}