apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-clusterrole
rules:
- apiGroups: ["build.openshift.io"]
  resources:
     - "buildconfig"
     - "build"
  verbs: ["*"]